import type { Theme } from "./types";

export const darkTheme: Theme = {
  appBackground: "#0F172A",
  primaryTextColour: "#F1F5F9",
  card: "#1E293B",
  cardForeground: "#F8FAFC",
  muted: "#334155",
  mutedForeground: "#94A3B8",
  primary: "#60A5FA",
  primaryForeground: "#0F172A",
  border: "#334155",
  destructive: "#F87171",
  headerBg: "#1E293B",
  surface: "#1E293B",
  inputBg: "#334155",
  inputFocusBg: "#475569",
  placeholder: "#64748B",
  radius: "0.5rem",
  typeface: "'Manrope', 'Avenir Next', 'Segoe UI', sans-serif",
};

export const lightTheme: Theme = {
  appBackground: "#F8FAFC",
  primaryTextColour: "#0F172A",
  card: "#FFFFFF",
  cardForeground: "#0F172A",
  muted: "#F1F5F9",
  mutedForeground: "#64748B",
  primary: "#2563EB",
  primaryForeground: "#FFFFFF",
  border: "#E2E8F0",
  destructive: "#DC2626",
  headerBg: "#FFFFFF",
  surface: "#F1F5F9",
  inputBg: "#FFFFFF",
  inputFocusBg: "#FFFFFF",
  placeholder: "#94A3B8",
  radius: "0.5rem",
  typeface: "'Manrope', 'Avenir Next', 'Segoe UI', sans-serif",
};
